(assert (char? #\a))
(assert (not (char? 1)))
(assert (not (char? (cons 1 2))))
(assert (not (char? "a")))

(assert (char= #\a #\a))
(assert (char>= #\a #\a))
(assert (char<= #\a #\a))
(assert (char<  #\a #\b))
(assert (char>  #\b #\a))
(assert (char<= #\a #\b))
(assert (char>= #\b #\a))
(assert (char/= #\b #\a))

(assert (not (char/= #\a #\a)))
(assert (not (char< #\a #\a)))
(assert (not (char> #\a #\a)))
(assert (not (char>=  #\a #\b)))
(assert (not (char<=  #\b #\a)))
(assert (not (char> #\a #\b)))
(assert (not (char< #\b #\a)))
(assert (not (char= #\b #\a)))

(assert (= 97 (char->int #\a)))
(assert (char= #\a (int->char 97)))

(assert (alphabetic? #\a))
(assert (alphanum? #\a))
(assert (alphanum? #\1))
(assert (numeric? #\1))
(assert (not (numeric? #\a)))
(assert (not (alphabetic? #\1)))
(assert (not (alphanum? #\,)))


;; Delimiters are valid character literals too; the reader used to choke on
;; these because the token scanner stopped at the delimiter.
(assert (char= #\( (string-ref "(" 0)))
(assert (char= #\) (string-ref ")" 0)))
(assert (char= #\" (string-ref "\"" 0)))
(assert (char= #\; (string-ref ";" 0)))
(assert (char= #\# (string-ref "#" 0)))
(assert (char= #\  #\space))
(assert (= 40 (char->int #\()))
(assert (equal? (list #\( #\)) (string->list "()")))
