(assert (char? #\a))
(assert (not (char? 1)))
(assert (not (char? (cons 1 2))))
(assert (not (char? "a")))

(assert (char= #\a #\a))
(assert (char>= #\a #\a))
(assert (char<= #\a #\a))
(assert (char<  #\a #\b))
(assert (char>  #\b #\a))
(assert (char<= #\a #\b))
(assert (char>= #\b #\a))
(assert (char/= #\b #\a))

(assert (not (char/= #\a #\a)))
(assert (not (char< #\a #\a)))
(assert (not (char> #\a #\a)))
(assert (not (char>=  #\a #\b)))
(assert (not (char<=  #\b #\a)))
(assert (not (char> #\a #\b)))
(assert (not (char< #\b #\a)))
(assert (not (char= #\b #\a)))

(assert (= 97 (char->int #\a)))
(assert (char= #\a (int->char 97)))

(assert (alphabetic? #\a))
(assert (alphanum? #\a))
(assert (alphanum? #\1))
(assert (numeric? #\1))
(assert (not (numeric? #\a)))
(assert (not (alphabetic? #\1)))
(assert (not (alphanum? #\,)))

