(assert-error (eq?1 2 3))
(assert-error (equal?1 2 3))

(assert (eq? 1 1))
(assert (eq? 'a 'a))
(assert (eq? 1.0 1.0))
(assert (eq? #\a #\a))
(assert (eq? #f #f))
(assert (eq? nil nil))
(assert (eq? #t #t))
(assert (not (eq? 1 2)))
(assert (not (eq? "a" "a")))
(assert (not (eq? 'a 'b)))
(assert (not (eq? '(1 2) '(1 2))))

(assert (equal? 1 1))
(assert (equal? 'a 'a))
(assert (equal? "a" "a"))
(assert (equal? 1.0 1.0))
(assert (equal? #\a #\a))
(assert (equal? #f #f))
(assert (equal? '(1 2) '(1 2)))

(assert (not (equal? 1 2)))
(assert (not (equal? 'a 'b)))
(assert (not (equal? "a" "b")))
(assert (not (equal? '(1 2 3) '(1 2))))
